version: "3.9"

services:
  hackernews-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackernews-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    restart: unless-stopped
